- name: Create Full Backup of db server to Backup Server
  ansible.builtin.shell: |
    pg_basebackup --host={{ db_ip }} --username={{ backupuser }} --port={{ pgport }} --format=tar --gzip --wal-method=stream --manifest-checksums={{ checksum_algorithm }} --pgdata={{ pgbkup }}/full_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}
  register: full_backup_result
  retries: 3
  delay: 30
  until: full_backup_result.rc == 0

- name: Debug output
  ansible.builtin.debug:
    var: full_backup_result.stdout
